sequenceiq/docker-ambari

ambari-server/start-server

Netstat should check only listening ports

---

ambari-server/Dockerfile

@martonsereg 
added ambari-start-stop plugn

1.7.0 consul restart

---

ambari-server/start-server

configurable postgres added

---

ambari-server/start-server

db init waits for db server to be available

---

ambari-server/start-agent
ambari-server/start-server

change hostname resolution on GCP

---

ambari-server/Dockerfile
ambari-server/start-agent

let consul resolve ambari server

---

ambari-server/ambari.repo

Ambari 2.1 is at build 730 already. I got this URL from the devs to stay on the latest available build

Use the latest available build as per dev advice

---

ambari-server/Dockerfile

do not use the docker0 interface

---

ambari-functions
ambari-server/Dockerfile
ambari-server/ambari.repo

I noticed that the ambari-functions weren't working with the consul based images. I made these changes as a stop-gap.

Built a 2.1 image using serf

---

ambari-server/Dockerfile

@akanto 
On GCP terasort of 2 TB finished, on AWS and Azure the pam test succeeded, OpenStack is not tested. After merge I'll move the change to all cb related branch.
centos                                 6.6                 8b44529354f3        11 weeks ago        202.6 MB
centos                                 7.1.1503            f1dade627e25        11 weeks ago        212.1 MB
sequenceiq/pam                         centos-6.5          2e0b6343afc8        4 months ago        923.5 MB

stock centos 6.6 as base image

---

ambari-server/ambari.repo

Put in the repo for Ambari 2.1.1. Tested with amb-deploy-cluster.

Moved to Ambari 2.1.1

---

ambari-functions

Small change to enable docker guest hostname lookups on docker host.

Expose DNS port on Consul server to enable name resolution on host os.

---

ambari-server/Dockerfile

@akanto @martonsereg 
in favor of Azure..

increase pkg install timeout to 40 mins

---

ambari-server/Dockerfile

Move Zeppelin from the warmup image

---

ambari-server/public-hostname.sh

configurable CLOUD_PROVIDER for public host name

---

ambari-server/start-agent

Removed call to non-existing method

---

ambari-agent/Dockerfile
ambari-agent/init/init-agent.sh

CLOUD-50459 ability to set up the ambari server location

---

ambari-server/init/init-server.sh

ambari server setup should use $POSTGRES_DB

---

ambari-agent/init/init-agent.sh
ambari-server/init/init-server.sh

CLOUD-50403 added switch for nameserver config

---

ambari-base/Dockerfile

CLOUD-52775 Change SSHD port to 2022

---

ambari-base/Dockerfile

CLOUD-52775 Revert SSHD port manipulation

---

ambari-agent/Dockerfile
ambari-server/Dockerfile

CLOUD-52775 Update base image version

---

ambari-server/shell/install-cluster.sh

CLOUD-53040 Update blueprint url
